### ISSUE TITLE
[SETUP] Lux defaults to Pandas when there are no valid actions defined.

### ISSUE THREAD

**Issue by jonozw** [lux-org/lux#284] opened 2021-02-22 01:36 UTC
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\formatters.py:345: UserWarning:
Lux defaults to Pandas when there are no valid actions defined.

1. install lux according the document
```
pip install lux-api

# active Jupyter notebook extension
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
2. run the demo code from readme.md
```
import lux
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/college.csv")
df
```
and then I cannot get the `Toggle Pandas/Lux` button, and see below warning message
```
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\formatters.py:345: UserWarning:
Lux defaults to Pandas when there are no valid actions defined.
```

please tell me what I am doing wrong, thanks

**Comment by dorisjlee** [comment] 2021-02-22 03:21
Hi @jonozw, 

Thanks for reporting this issue. It is very strange that you are seeing the warning, which is typically associated with when the dataframe is empty or has only a few columns/rows. 
Can you provide a screenshot of what you see when you print the dataframe `df`? Do you see the Pandas view showing the full data table like below? 
![image](https://user-images.githubusercontent.com/5554675/108652165-73e78500-74fe-11eb-942f-bf2a61a27ccd.png)
If you try printing out `df.recommendation`, what are the results that you get?

I also notice that you are using Anaconda, so you may want to install via conda: 
```
conda install -c conda-forge lux-api
```
followed by the Jupyter notebook setup commands:
```
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
If this doesn't work, please also let us know whether you are using Jupyter notebook or lab and the version that you are using. 

Thanks!

**Comment by jonozw** [comment] 2021-02-22 08:05
##Enviroment: 
1. Anaconda3:  2020.11
2. Jupyter Notebook: 6.2.0
3. Python 3.8.5

![图片](https://user-images.githubusercontent.com/30031941/108679534-a659a800-7527-11eb-907c-33577c9dab16.png)

**Comment by jonozw** [comment] 2021-02-22 08:06
(base) X:\tmp>jupyter nbextension install --py luxwidget
Installing C:\ProgramData\Anaconda3\lib\site-packages\luxwidget\nbextension/static -> luxwidget
Up to date: C:\ProgramData\jupyter\nbextensions\luxwidget\extension.js
Up to date: C:\ProgramData\jupyter\nbextensions\luxwidget\index.js
Up to date: C:\ProgramData\jupyter\nbextensions\luxwidget\index.js.map
- Validating: ok

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable luxwidget --py


(base) X:\tmp>jupyter nbextension enable --py luxwidget
Enabling notebook extension luxwidget/extension...
      - Validating: ok

**Comment by jonozw** [comment] 2021-02-22 08:12
it worked....

1. at the begining, I install lux with pip, then I got the error message. 
2. I modify the code form df->df.head()
3. I uninstall the lux with pip and reinstall it with conda
4. modify the code to df again
5. it worked...

I am not sure whether or not the first error message was caused by df.head()....

but now it worked, I like this project, thanks:)

**Comment by dorisjlee** [comment] 2021-02-22 08:44
Hi @jonozw, 
Yes I think the first warning message is likely caused by `df.head()`, since the dataframe is not big enough to generate recommendations. It is great to hear that this is working for you now. I'll close this issue for now, feel free to let us know if there are any issues and questions that come up!

**Closed** 2021-02-22 08:44 UTC
Labels: setup
