### ISSUE TITLE
[BUG] User-provided Index causes KeyError in Pandas Execution

### ISSUE THREAD

**Issue by briankim1027** [lux-org/lux#181] opened 2020-12-19 10:36 UTC
1. i installed as follow guideline in jupyter notebook cell
    !pip install lux-api
    !jupyter nbextension install --py luxwidget
    !jupyter nbextension enable --py luxwidget

2. import lux and read csv file then call dataframe
   i got an message as follows.  

how can i fix it? thank U

C:\Users\brian\anaconda3\lib\site-packages\IPython\core\formatters.py:345: UserWarning:
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
Please report the following issue on Github: https://github.com/lux-org/lux/issues 

C:\Users\brian\anaconda3\lib\site-packages\lux\core\frame.py:711: UserWarning:Traceback (most recent call last):
  File "C:\Users\brian\anaconda3\lib\site-packages\lux\core\frame.py", line 663, in _repr_html_
    self.maintain_recs()
  File "C:\Users\brian\anaconda3\lib\site-packages\lux\core\frame.py", line 494, in maintain_recs
    custom_action_collection = custom_actions(rec_df)
  File "C:\Users\brian\anaconda3\lib\site-packages\lux\action\custom.py", line 73, in custom_actions
    recommendation = lux.actions.__getattr__(action_name).action(ldf, args)
  File "C:\Users\brian\anaconda3\lib\site-packages\lux\action\univariate.py", line 84, in univariate
    vlist = VisList(intent, ldf)
  File "C:\Users\brian\anaconda3\lib\site-packages\lux\vis\VisList.py", line 43, in __init__
    self.refresh_source(self._source)
  File "C:\Users\brian\anaconda3\lib\site-packages\lux\vis\VisList.py", line 313, in refresh_source
    ldf.executor.execute(self._collection, ldf)
  File "C:\Users\brian\anaconda3\lib\site-packages\lux\executor\PandasExecutor.py", line 97, in execute
    PandasExecutor.execute_aggregate(vis, isFiltered=filter_executed)
  File "C:\Users\brian\anaconda3\lib\site-packages\lux\executor\PandasExecutor.py", line 171, in execute_aggregate
    vis._vis_data = vis.data[[groupby_attr.attribute, "Record"]]
  File "C:\Users\brian\anaconda3\lib\site-packages\pandas\core\frame.py", line 2912, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "C:\Users\brian\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "C:\Users\brian\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1304, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['Record'] not in index"

**Comment by thyneb19** [comment] 2020-12-20 04:04
Hi @briankim1027, thank you for trying out Lux! Seems like there is an issue with the way the data for a visualization is being gathered. Would you be able to share a sample of the dataset or a similar dataset so we can try to reproduce the error for testing?

Thank you!

**Comment by briankim1027** [comment] 2020-12-20 13:02
Thank you.
I don't know the way to share my data file in github.
So I would share the my google drive link
 https://drive.google.com/file/d/1gOyO56Z8166WQjQosyw4DSvw0jUDnHna/view?usp=sharing 
training_resample.csv is the size reduction file.
Thanks,

**Comment by dorisjlee** [comment] 2020-12-20 13:38
Hi @briankim1027, Thank you for sending the data sample. I was able to load in your data correctly:
![image](https://user-images.githubusercontent.com/5554675/102714645-102cba00-430b-11eb-8f8a-f9494f6ee72c.png)
However, if I add the parameter `index_col=0`, then I get the same error, is that what you are seeing on your end too? 
```python
df = pd.read_csv("traing_resample.csv",index_col=0)
```

If that is the case, then maybe you could try loading in your data first, then dropping the first ID column by doing this:
```python
df = pd.read_csv("traing_resample.csv")
df = df.drop(columns=["id"])
```
Please let us know if that fixes the issue for you. Thanks!

**Comment by briankim1027** [comment] 2020-12-20 15:09
ThankU @dorisjlee, your quick response.
When I got an error message, I executed the code cell in Colab as follows.

```
data_dir = Path('/content/drive/MyDrive/input/')
trn_file = data_dir / 'train.csv' (it is the original dataset)
trn = pd.read_csv(trn_file, index_col=0)
trn
```
According to your mentioned above, I also executed the cell correctly.
But, when I try to execute set_index, I got the same error. 

```
trn = train.set_index(['id'])
trn
```
Anyway, Thanks!

**Comment by thyneb19** [comment] 2020-12-21 17:28
Hi @briankim1027, thank you for sharing your code which led to the error. Currently the behavior you are seeing is unexpected and we are working on a fix for this bug asap.

**Comment by dorisjlee** [comment] 2021-01-09 12:01
Hi @briankim1027,
We were able to fix the issues caused by the dataframe index mentioned above.
You can access these changes by upgrading to [the latest version of Lux](https://pypi.org/project/lux-api/0.2.2/):
```python
pip install --upgrade lux-api
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
Please let us know if this addresses the issue mentioned above. Feel free to ping us again if there are any other questions that come up! Thanks!

**Closed by dorisjlee** 2021-01-09 12:01 UTC
Labels: bug
