### ISSUE TITLE
[BUG] Mixed dtype not supported for pd.read_excel

### ISSUE THREAD

**Issue by belkmouf** [lux-org/lux#168] opened 2020-11-30 23:13 UTC
################################################################################
![error Lux](https://user-images.githubusercontent.com/25062193/100676842-ae92b480-3337-11eb-9d8c-fcb631037285.PNG)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\formatters.py:345: UserWarning:
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
Please report the following issue on Github: https://github.com/lux-org/lux/issues 

C:\ProgramData\Anaconda3\lib\site-packages\lux\core\frame.py:709: UserWarning:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\core\frame.py", line 661, in _repr_html_
    self.maintain_recs()
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\core\frame.py", line 492, in maintain_recs
    custom_action_collection = custom_actions(rec_df)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\action\custom.py", line 73, in custom_actions
    recommendation = lux.actions.__getattr__(action_name).action(ldf, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\action\univariate.py", line 84, in univariate
    vlist = VisList(intent, ldf)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\vis\VisList.py", line 43, in __init__
    self.refresh_source(self._source)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\vis\VisList.py", line 313, in refresh_source
    ldf.executor.execute(self._collection, ldf)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\executor\PandasExecutor.py", line 97, in execute
    PandasExecutor.execute_aggregate(vis, isFiltered=filter_executed)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\executor\PandasExecutor.py", line 228, in execute_aggregate
    vis._vis_data = vis.data.sort_values(by=groupby_attr.attribute, ascending=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 5307, in sort_values
    indexer = nargsort(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\sorting.py", line 301, in nargsort
    indexer = non_nan_idx[non_nans.argsort(kind=kind)]
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by dorisjlee** [comment] 2020-12-01 09:16
Hi @belkmouf, This is likely happening because your Excel data contains one or more column that has [mixed data types](https://stackoverflow.com/questions/42477572/sort-values-method-in-pandas). I don't have access to your data, but I was able to reproduce the error that you are seeing with a different Excel file. 
![image](https://user-images.githubusercontent.com/5554675/100719728-fe38b500-33f7-11eb-8fda-fd9ade19f87f.png)
For example, here the "Car Type" column contains both `int` and `str` values (i.e., mixed type) and is recognized as an `object` type. 
![image](https://user-images.githubusercontent.com/5554675/100720435-f3caeb00-33f8-11eb-9c2e-3710869bf67b.png)

We can fix this by converting that column to a `str` type, which resolves the error.
![image](https://user-images.githubusercontent.com/5554675/100720051-68e9f080-33f8-11eb-8f9b-ee47bdae49bb.png)
Alternatively, you can also specify a `converter` or `dtype` in the `read_excel` to ensure that the data type is specified correctly. See the [Pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html) or [this post](https://stackoverflow.com/questions/32591466/python-pandas-how-to-specify-data-types-when-reading-an-excel-file) for more details.

**Comment by dorisjlee** [comment] 2020-12-01 09:20
@jinimukh: Could we add a better warning message to flag issues with the input dataframe if the dataframe contains mixed dtypes? Similar to what we do with type detection warning date type columns.

**Comment by dorisjlee** [comment] 2020-12-12 09:40
This error is also reproduced in the [Kaggle DS survey data](https://www.kaggle.com/c/kaggle-survey-2020/data) since the first row is string columns.
![image](https://user-images.githubusercontent.com/5554675/101980521-f3f0a380-3ca0-11eb-9e8e-f5023a073901.png)

**Comment by dorisjlee** [comment] 2021-01-09 11:28
Hi @belkmouf, 
@jinimukh fixed this bug in our most recent release. 
You can access these updated changes by upgrading to [the latest version of Lux](https://pypi.org/project/lux-api/0.2.2/):
```python
pip install --upgrade lux-api
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
Please let us know if this addresses the issue mentioned above. 
I'll close this issue for now, but feel free to open a new issue if there are any other questions that come up!

**Closed by dorisjlee** 2021-01-09 11:28 UTC
Labels: bug, pandas
