### ISSUE TITLE
saving Vis images

### ISSUE THREAD

**Issue by deepikamittal** [lux-org/lux#335] opened 2021-03-31 09:10 UTC
I am using lux library for visualizations.
I have a Vis object and want to save the image.
I tried using save_as_html but i am getting the following error:
'Vis' object has no attribute 'save_as_html'.
How can i save the image?
Below attached the screenshot of the code.
![Capture1](https://user-images.githubusercontent.com/68030226/113120096-da16a480-922e-11eb-89a4-f7d5ba26f924.PNG)

**Comment by dorisjlee** [comment] 2021-04-03 17:06
Hi @deepikamittal, Thank you for your question! Currently, the save_as_html feature can only be called on the dataframe. The reason why we did this is that when it is called on the dataframe, we export all the visualizations into a presentable HTML. But when you have a single Vis, it is much easier to save the visualization directly into HTML, PNG, or whichever format you like.

The easiest way to do this is by right-clicking on the figure and save the image as a PNG.
![image](https://user-images.githubusercontent.com/5554675/113485512-73201680-94e0-11eb-8953-22eea86ccc3e.png)
To export to other formats, you might want to first export your vis to the plotting code (e.g., `print(num_v.to_code(language="altair"))`) like this:
![image](https://user-images.githubusercontent.com/5554675/113485753-d1012e00-94e1-11eb-9217-52e76f322dee.png)
You can set the `language` as any one of `matplotlib`, `altair` or `vegalite`. 

Then using the code written in those libraries, you should be able to save in whichever format you like. Here is an example of how you can [export your visualization to code](https://lux-api.readthedocs.io/en/latest/source/guide/export.html#exporting-visualizations-as-code).

Let us know if this solves the problem for you.

**Comment by deepikamittal** [comment] 2021-04-06 07:42
Hi @dorisjlee . Thank you for your response. 
I did export it to other format, i converted it to matplotlib code. but not able to see the visualisation. some error is coming.
Attaching the screenshot
![Capture](https://user-images.githubusercontent.com/68030226/113675970-8c3fe780-96d9-11eb-9664-58e55bb4f4bd.PNG)
![Capture2](https://user-images.githubusercontent.com/68030226/113676004-93ff8c00-96d9-11eb-82ed-724dccd2d7ae.PNG)

**Comment by dorisjlee** [comment] 2021-04-07 22:17
Hi @deepikamittal, Thanks for clarifying the details. To convert to matplotlib code, you can do `print (num_v.to_matplotlib_code())`. The `to_matplotlib` option that you were using turns it into an embeddable PNG, but it is not the code that can be used to generate the visualization.

**Comment by deepikamittal** [comment] 2021-04-14 05:49
Hi @dorisjlee . Thank you for your response. It is working now.

**Comment by deepikamittal** [comment] 2021-04-14 06:02
@dorisjlee - Also there is a difference in the visualizations created by lux and created by code through matplotlib. May be the scaling issue is there. Can you please help me on this. 
Attaching the screenshot of both visualizations. Also the screenshot of the code which is in built used when we convert it to matplotlib code.

![Capture](https://user-images.githubusercontent.com/68030226/114661655-f4fc1500-9d14-11eb-9a13-9597b0b38ada.PNG)
![Capture1](https://user-images.githubusercontent.com/68030226/114661668-fb8a8c80-9d14-11eb-8c7a-50a53a4a6469.PNG)
![Capture2](https://user-images.githubusercontent.com/68030226/114661675-ffb6aa00-9d14-11eb-8f99-92593e161274.PNG)

**Comment by dorisjlee** [comment] 2021-04-19 05:51
Hi @deepikamittal, Thanks for raising this issue. @caitlynachen will be taking a look at why the output code looks different from the code from the widget. 

In addition, based on your feedback that `to_matplotlib` should return the matplotlib code, we fixed this in #359, so you should be able to use `to_matplotlib` in the latest release for Lux. You can install the latest release by doing: 
```
pip install --upgrade lux-api
```
followed by the [setup instructions](https://github.com/lux-org/lux#installation--setup).

**Comment by deepikamittal** [comment] 2021-04-28 06:04
Hi @dorisjlee . Thanks for the update. 
Now i have implemented lux on jupyter notebook and its working correctly.
But while integrating the same code in flask, it is giving error.
' Lux dataframe object does not have  attribute unique'.
Below attached is the screenshot. Please help me.
![Inkedimage_LI](https://user-images.githubusercontent.com/68030226/116354166-a327b480-a815-11eb-856e-34e01b32a9ba.jpg)

**Comment by deepikamittal** [comment] 2021-04-28 06:06
Hi @caitlynachen . Did you saw why the output visualization is different from the widget visualization. Please help me.
Thank you.

**Comment by dorisjlee** [comment] 2021-04-28 13:14
Hi @deepikamittal, Could you specify the code that you ran and the dataset that you used to reproduce the `unique` error? This will help us debug the issue that you are looking at.

**Comment by deepikamittal** [comment] 2021-04-29 05:54
Hi @dorisjlee , Please find attached the code. I am not able to attach the dataset. However, any dataset can  e taken.

![Capture](https://user-images.githubusercontent.com/68030226/116507242-84402580-a8dc-11eb-861f-abe78b70f93f.PNG)

**Comment by deepikamittal** [comment] 2021-04-29 05:57
Hi Doris Lee,

I am not able to attach the dataset and .py file on Github. Please find
attached the code and dataset..

Thanks
Deepika

**Comment by deepikamittal** [comment] 2021-04-29 08:27
Hi @dorisjlee, the images are saved at a particular path, however, integrating same thing on flask, i am not getting visualizations displayed on html. Is this some issue with lux or it a problem of html or flask. Please help me.
Below is the attached screenshot for reference.


![image](https://user-images.githubusercontent.com/68030226/116522330-b492be80-a8f2-11eb-8f32-e141276b3bb9.png)

**Comment by dorisjlee** [comment] 2021-04-30 01:40
Hi @deepikamittal, Thanks for attaching this info. It's a bit difficult to debug what went wrong, whether this is an issue with Lux or something that is an issue with Flask. Could you send me an email at [dorisjunglinlee@gmail.com](dorisjunglinlee@gmail.com) so that we hop on a call to debug this? I might be more help after understanding what your current setup is like and what might be causing the issue.

**Comment by dorisjlee** [comment] 2021-08-01 16:37
Hi @deepikamittal, We're closing this for now, but please let us know if you run into any other issues!

**Closed by dorisjlee** 2021-08-01 16:37 UTC
Labels: bug, export
