### ISSUE TITLE
Lux does not currently support dataframes with hierarchical indexes.

### ISSUE THREAD

**Issue by danilosantiago** [lux-org/lux#201] opened 2021-01-06 14:40 UTC
C:\Anaconda3\lib\site-packages\IPython\core\formatters.py:345: UserWarning:
Lux does not currently support dataframes with hierarchical indexes.
Please convert the dataframe into a flat table via `pandas.DataFrame.reset_index`

**Comment by dorisjlee** [comment] 2021-01-08 11:53
Duplicate of #40.

**Closed** 2021-01-09 12:07 UTC
