### ISSUE TITLE
[BUG] "Undefined" chart caused by special character period `.` in column name

### ISSUE THREAD

**Issue by ehsong** [lux-org/lux#175] opened 2020-12-07 20:30 UTC
I have a data set with categorical variables, but lux is not displaying them properly. Instead of the distribution of the categorical variables, they are lumped to 'undefined'. I tried dropping NaNs but this did not fix the problem.

My data set looks like this:

![analysis_total_data_-_Jupyter_Notebook_and_Movie_Finder_-_Chrome_Web_Store](https://user-images.githubusercontent.com/5554659/101401903-da59f100-3887-11eb-8a47-239cf82aae0f.jpg)

The toggle result was:

![analysis_total_data_-_Jupyter_Notebook](https://user-images.githubusercontent.com/5554659/101401970-f362a200-3887-11eb-9d81-078c58e27dac.jpg)

I was expecting for the first chart to have categories Evident, Somewhat Evident, Indicator Skipped etc...but it was all lumped to 'undefined'. The data type is non-null object

![analysis_total_data_-_Jupyter_Notebook](https://user-images.githubusercontent.com/5554659/101402259-60763780-3888-11eb-86ba-ec87d189a1af.jpg)

**Comment by dorisjlee** [comment] 2020-12-08 08:36
Hi @ehsong, Thank you for your interest in Lux! I was able to mock up a sample of your dataset and reproduce the problem that you are seeing. The issue is caused by the period in each of the column names (this is a [known issue](https://github.com/altair-viz/altair/issues/284) in Altair, which is a library that Lux uses for plotting).
Below is the visualization before and after removing the period: 

<div>
<img src="https://user-images.githubusercontent.com/5554675/101458060-4e23f880-3971-11eb-8f76-f51042a4750c.png" width="45%">
<img src="https://user-images.githubusercontent.com/5554675/101458224-917e6700-3971-11eb-89ca-7f80e73eb395.png" width="45%">
<div>

The easier fix on your end is to simply remove all the `.` in the column names in your dataframe. Based on the screenshot that you've posted, it looks like the `.` corresponds to every last character of every column in your dataframe. So you could do something like this to replace all the periods in the column names.
```python
df.columns = df.columns.str.replace(".","")
```
![image](https://user-images.githubusercontent.com/5554675/101458942-87a93380-3972-11eb-9b9f-d26613c786e1.png)

Please let us know if this fixes the issue you are seeing for "undefined" displaying the bar charts.

We will also fix things on our end to better support special characters in column names, as well as long column names, (like the ones in your dataset) in the future. Thanks for bringing this issue to our attention!

**Comment by dorisjlee** [comment] 2020-12-27 12:03
Hi @ehsong, We've resolved the issue with the special characters in column names. We've also abbreviated long column names so that they are displayed properly on the charts. We will be incorporating this into the next release. Thanks!
![image](https://user-images.githubusercontent.com/5554675/103170317-57bcc400-487e-11eb-8a16-293f134b030f.png)

**Closed by dorisjlee** 2020-12-27 12:03 UTC
Labels: bug
